// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"github.com/simple-zero-go/app/wx/service/internal/conf"
	"github.com/simple-zero-go/app/wx/service/internal/server"
	"github.com/simple-zero-go/app/wx/service/internal/service"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, data *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	wxSysService := service.NewWxSysService()
	httpServer := server.NewHTTPServer(confServer, wxSysService, logger)
	grpcServer := server.NewGRPCServer(confServer, wxSysService, logger)
	app := newApp(logger, httpServer, grpcServer)
	return app, func() {
	}, nil
}
